default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.256"
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude: "tests/openapi/typescript_converter/test_converter"
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        exclude: "_templates"
  - repo: https://github.com/python-formate/flake8-dunder-all
    rev: v0.2.2
    hooks:
      - id: ensure-dunder-all
        exclude: "test*|examples*|tools"
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.16.5
    hooks:
      - id: slotscheck
        exclude: "test_*|docs"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        exclude: "test_apps|tools|docs"
        additional_dependencies:
          [
            aiosqlite,
            asyncpg,
            beanie,
            beautifulsoup4,
            brotli,
            click,
            fakeredis,
            fast-query-parsers,
            freezegun,
            fsspec,
            httpx,
            jsbeautifier,
            hypothesis,
            mako,
            mongomock_motor,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            opentelemetry-sdk,
            piccolo,
            picologging,
            pydantic,
            pydantic_factories,
            pydantic_openapi_schema,
            pytest,
            pytest-lazy-fixture,
            pytest-mock,
            python-dotenv,
            python-jose,
            pytest_docker,
            pyyaml,
            rich,
            sqlalchemy>2.0,
            starlette,
            structlog,
            tortoise-orm,
            types-beautifulsoup4,
            types-freezegun,
            types-pyyaml,
            types-redis,
            uvicorn,
          ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.299
    hooks:
      - id: pyright
        exclude: "test_apps|tools|docs|_openapi"
        additional_dependencies:
          [
            aiosqlite,
            asyncpg,
            beanie,
            beautifulsoup4,
            brotli,
            click,
            fakeredis,
            fast-query-parsers,
            freezegun,
            fsspec,
            httpx,
            hypothesis,
            jsbeautifier,
            mako,
            mongomock_motor,
            msgspec,
            multidict,
            opentelemetry-instrumentation-asgi,
            opentelemetry-sdk,
            piccolo,
            picologging,
            pydantic,
            pydantic_factories,
            pydantic_openapi_schema,
            pytest,
            pytest-lazy-fixture,
            pytest-mock,
            pytest_docker,
            python-dotenv,
            python-jose,
            pyyaml,
            rich,
            sqlalchemy>2.0,
            starlette,
            structlog,
            tortoise-orm,
            types-beautifulsoup4,
            types-freezegun,
            types-pyyaml,
            types-redis,
            uvicorn,
          ]
  - repo: local
    hooks:
      - id: sphinx-lint
        name: sphinx-lint
        language: python
        entry: sphinx-lint
        additional_dependencies: [sphinx-lint]
        types: [rst]
